guzzle/psr7

- src/CachingStream.php
- tests/CachingStreamTest.php
@jeremeamia @jeskew
Addresses https://github.com/aws/aws-sdk-php/issues/587
> Allow forward seeking in caching stream

- src/Uri.php
- tests/UriTest.php
> Fixed Uri::resolve dropping user info from the base uri

- src/Uri.php
- tests/UriTest.php
> fixes #47 - proper handling of hier-part

- README.md
I found that this code does not work as described in README.
> Fix REAME (DroppingStream)

- src/functions.php
> accept integers as valid resource type

- src/functions.php
- tests/MultipartStreamTest.php
> Tests for serializing scalars in the MultipartStream

- src/functions.php
- tests/FunctionsTest.php
Follow https://github.com/guzzle/psr7/pull/54#issuecomment-197418414
> [RFR] Extend modify_request support to ServerRequest

- src/Request.php
- src/functions.php
- tests/RequestTest.php
Fixes #86 and the typical `'0'` problem for the Request body and getRequestTarget.
> Fix request phpdoc and '0' problem

- src/Uri.php
- tests/UriTest.php
- Fix Uri::resolve when base path has no slash
- Fix Uri::resolve handling of fragment
- Add tests for dot segments in query/fragment taken from RFC 3986 that have been missing in the tests
- New implemenation is much closer to the pseudo code in http://tools.ietf.org/html/rfc3986#section-5.2 and more logical
> Fix Uri::resolve for edge cases

- src/Request.php
- src/Response.php
- tests/RequestTest.php
- tests/ResponseTest.php
> fix request/response constructor to not read stream

- composer.json
- src/Uri.php
- tests/UriTest.php
According to php-fig/fig-standards#756
> Each URI modification should result in a valid URI

- src/Request.php
by this guard, $this->uri cannot be null.
```php
if (!($uri instanceof UriInterface)) {
$uri = new Uri($uri);
}
```
> $uri cannot be null

- src/functions.php
- tests/FunctionsTest.php
> Add test for fix parse_response without reason and delimiting space

- CHANGELOG.md
- src/functions.php
https://github.com/guzzle/psr7/issues/145
> Fix #145 Add response first-line to response string exception

- src/StreamWrapper.php
- tests/StreamWrapperTest.php
Related issue:
https://github.com/guzzle/psr7/issues/98
> add StreamWrapper::stream_cast method

- tests/AppendStreamTest.php
- tests/FunctionsTest.php
- tests/StreamTest.php
- tests/UploadedFileTest.php
This will provide us better errors messages :)
> Use dedicated PHPUnit assertions

- composer.json
- phpunit.xml.dist
- tests/AppendStreamTest.php
- tests/BaseTest.php
- tests/BufferStreamTest.php
- tests/CachingStreamTest.php
- tests/DroppingStreamTest.php
- tests/FnStreamTest.php
- tests/FunctionsTest.php
- tests/InflateStreamTest.php
- tests/LazyOpenStreamTest.php
- tests/LimitStreamTest.php
- tests/MultipartStreamTest.php
- tests/NoSeekStreamTest.php
- tests/PumpStreamTest.php
- tests/RequestTest.php
- tests/ResponseTest.php
- tests/ServerRequestTest.php
- tests/StreamDecoratorTraitTest.php
- tests/StreamTest.php
- tests/StreamWrapperTest.php
- tests/UploadedFileTest.php
- tests/UriNormalizerTest.php
- tests/UriResoverTest.php
- tests/UriTest.php
- tests/bootstrap.php
Reopening #173 as requested by @Tobion
> Support PHPUnit versions 5 and 6

- src/ServerRequest.php
- tests/ServerRequestTest.php
> Use parse_url to extract port from host (Support IPv6 local loopback)

- src/functions.php
See https://github.com/guzzle/psr7/pull/207#discussion_r194715848
> revert wrong phpdoc change of #207

- README.md
- src/Uri.php
- tests/UriTest.php
> created withQueryValues method

- src/Request.php
- tests/RequestTest.php
https://github.com/guzzle/psr7/issues/223
> fix Request::withUri()

- CHANGELOG.md
- src/functions.php
> Add 3gp extension to mime types

- src/functions.php
- tests/FunctionsTest.php
According to these:
https://github.com/guzzle/guzzle/pull/2081
https://github.com/guzzle/guzzle/pull/2227
> Get the summary of a body only if it is readable

- composer.json
> Suggest zendframework/zend-httphandlerrunner to emit PSR-7 responses

- composer.json
The factory is implemented, so let Composer know we provide it.
> [2.x] Provide psr/http-factory-implementation

- .travis.yml
> Allow HHVM to fail

- src/functions.php
- tests/FunctionsTest.php
> Handle `Set-Cookie` in `str` correctly

- src/MessageTrait.php
- tests/RequestTest.php
- tests/ResponseTest.php
Reported on https://github.com/guzzle/guzzle/issues/1870
Whitelisted / blacklisted a bunch of characters based on https://tools.ietf.org/html/rfc7230#section-3.2
> Added header fields validation against not allowed characters

- src/functions.php
- tests/FunctionsTest.php
> Handle multiple Set-Cookie in str() correctly by outputting them as separate headers for 1.x

- composer.json
Prefer suggesting active library over abandoned.
> prefer suggesting active library over abandoned

- src/AppendStream.php
- src/FnStream.php
- src/PumpStream.php
- src/Stream.php
- src/StreamDecoratorTrait.php
- tests/AppendStreamTest.php
- tests/FnStreamTest.php
- tests/PumpStreamTest.php
- tests/StreamDecoratorTraitTest.php
- tests/StreamTest.php
> allow exceptions to bubble in __toString with PHP 7.4

- .github/workflows/checks.yml
- composer.json
> Remove composer normalize dependency

- composer.json
- phpstan-baseline.neon
- tests/UriTest.php
Merges 1.x -> master up to the 0cddfcbdb4e0a078adf1794f68de79a57f4fb352 commit on 1.x, and also cherry-picks in 25f7f893f0b52b7b14e244a16679d72b1f0088de. After this PR is merged and so is https://github.com/guzzle/psr7/pull/370, then master should be green. I will then tackle merging the rest of the changes from 1.x into master.
---
EDIT: Changes from https://github.com/guzzle/psr7/pull/370 now included in here too.
> Merge v1 before static methods

- composer.json
> Drop ralouphie/getallheaders v2

- .gitattributes
- .github/workflows/static.yml
- .gitignore
- composer.json
- phpstan.neon.dist
- psalm-baseline.xml
- psalm.xml
- src/CachingStream.php
- src/UploadedFile.php
- vendor-bin/php-cs-fixer/composer.json
- vendor-bin/phpstan/composer.json
- vendor-bin/psalm/composer.json
Similar to https://github.com/guzzle/guzzle/pull/2825.
> Add psalm, update CI and fixed some deprecated calls. 

- .github/workflows/.editorconfig
- .github/workflows/integration.yml
- phpunit.xml.dist
- src/CachingStream.php
- src/Utils.php
- tests/Integration/ServerRequestFromGlobalsTest.php
- tests/Integration/server.php
This test should fail because of the bug found in #382
> Adding integration tests

- src/Uri.php
- tests/UriTest.php
Co-Authored-By: Alexey Shokov <alexey@shockov.com>. Replaces #297.
> Locale independent URL parsing

- src/Uri.php
- tests/UriTest.php
> Fix parsing Ipv6

- composer.json
Mimics PHPUnit version on 1.x. Upgrades `http-interop/http-factory-tests`.
> Upgraded dev-deps

- CHANGELOG.md
It is not that much that have changed.. right? It has mostly been major cleanups.
> Added changelog for 2.0 beta

- src/Response.php
> Add reason phrase for 308 http status code

- CHANGELOG.md
> Update date of release

- .github/FUNDING.yml
- .github/workflows/ci.yml
- .github/workflows/integration.yml
- LICENSE
- README.md
- composer.json
- vendor-bin/php-cs-fixer/composer.json
This PR should not be squash-merged, as to preserve the merge history.
> Merge 1.x -> master

- tests/UriResolverTest.php
This pull request adds a single additional testcase as described in [the related issue](https://github.com/guzzle/psr7/issues/433).
---
Closes #433.
> Add additional URL resolver test case

- CHANGELOG.md
The last 1.x release, for really reals. :trollface: 
---
After merge, I'll follow-up with a 1.x -> master branch merge and a 2.1.0 release PR.
> Release 1.8.3

- src/MultipartStream.php
> Dont put the full file body as filename

- CHANGELOG.md
- src/MessageTrait.php
- tests/RequestTest.php
> Release 2.1.2

- src/Stream.php
- tests/StreamTest.php
> Re-wrap exceptions thrown in fread into RuntimeExceptions

- .github/workflows/checks.yml
- .github/workflows/ci.yml
- .github/workflows/integration.yml
- .github/workflows/static.yml
- phpunit.xml.dist
> Fix integration tests to actually run

- src/Uri.php
- tests/UriTest.php
> Fix erroneous behaviour when combining host and relative path

- src/LazyOpenStream.php
see b4719a1466c0a07be786ed9950f34e8ccb39277a
> Remove the need for `AllowDynamicProperties` in LazyOpenStream
