src/Uri.php, tests/UriTest.php
Uri::applyParts() now validates the scheme so a Uri can not be instigated with an invalid scheme.
Changed Uri::getPort() to return null if the port is the default port for the scheme. See PSR-7 specification.
=> Updated Uri to prevent instigation with an invalid scheme

composer.json
This is the second implementation of the PSR 7 interfaces I met.
The first one is probably [phly/http](https://github.com/phly/http). While that tries to focus on the message interfaces, this package contains a lot of Stream implementations which makes it a good competitor.
See the rationale here: phly/http#65
=> Adds virtual package

src/Uri.php, tests/RequestTest.php, tests/UriTest.php
Closes #18.
This commit updates the Uri class to allow for relative paths. A leading
slash is now only added to a path when it is necessary in order to make
the URI valid: when there is a host and the URI is not '' and does not
start with '/'.
@jeremeamia @jeskew
=> Allowing relative URIs

composer.json, src/functions_include.php
Composer unconditionally "autoloads" files using `require` (see composer/composer#3003): this causes problems with globally-installed dependencies or where the composer autoload happens to be called more than once (see guzzle/guzzle#676).
One solution is to guard against function redeclaration using `function_exists()`, something that both guzzle/promises and React do (see [L4-7 in functions.php](https://github.com/guzzle/promises/blob/master/src/functions.php#L4-L7) and reactphp/promise#25, respectively).
The solution guzzle/promises currently uses does not work: PHP will attempt to load the functions before the conditional is evaluated. I've opted for the React solution, which is to point to a shim `functions_include.php` file that checks for the existence of the first function within …
=> Conditionally require functions.php

src/Response.php, tests/ResponseTest.php
Issue is described in guzzle/guzzle#1210.
If `(bool)$body === false` we have a not consistent reprenstation of the body in the `Response` object.
=> [Response] Fixing issue with body that cast to the boolean false

src/functions.php, tests/FunctionsTest.php
See issue #24. When used as a proxy server, the client sends the full URI (not only the relative one). This patch supports both and added a test.
Looking forward for your feedback/comments!
=> Fixes for issue-24 (support full URL's in requests, such as proxied requests)

CHANGELOG.md, src/CachingStream.php, tests/CachingStreamTest.php
This PR allows you to seek to a number of bytes before the end of a stream by passing a negative offset and SEEK_END to seek (to match the behavior of `fseek` on file handles). 
It also fixes the off-by-one error when seeking to the end of a `CachingStream` as reported in https://github.com/aws/aws-sdk-php/issues/809
=> Copy SEEK_END behavior from fseek

src/Response.php
This new status code has been approved by the IETF.  It is awaiting final publication and RFC number assignment.  According to Mark Nottingham, the IETF HTTP Working Group Chair, “you can start using it now.”
(I wouldn't be opposed to waiting until the final RFC is published before merging this)
- https://datatracker.ietf.org/doc/draft-ietf-httpbis-legally-restricted-status/
- http://thenextweb.com/dd/2015/12/21/theres-now-an-official-http-status-code-for-legal-takedowns-451/
=> Add HTTP 451 Unavailable For Legal Reasons

src/functions.php, tests/FunctionsTest.php
The `Host` HTTP header must contain the HTTP port when it is not standard. Without this patch, Guzzle fails to follow redirect properly when the URI uses a non-standard port.
=> added missing port to the Host when non-standard

tests/UriTest.php
This test case explains how to use library if you want to set 'base_url' with part of the path (e.g. http://foo.bar/api/) in the Client and append another part of the path (e.g. user/profile) in the Message thus to obtain request to full url (e.g. http://foo.bar/api/user/profile) with no replacements
=> additional test case for Uri resolving

src/CachingStream.php, tests/CachingStreamTest.php
There was an issue discovered [from aws-sdk-php](https://github.com/aws/aws-sdk-php/pull/903) that was causing `getimagesize()` to fail as seek was only reading to the end of a block instead of up to the requested offset.
This change fixes the issue.
=> Ensure all requested bytes are read when using seek on caching stream

src/InflateStream.php, tests/InflateStreamTest.php
A gzip file can have the original filename in the header. This pull request makes the InflateStream handle those cases, too.
=> Handle gzip format with a FNAME header

src/ServerRequest.php, src/UploadedFile.php, tests/ServerRequestTest.php, tests/UploadedFileTest.php
This is an implementation of ServerRequest and UploadedFIle and closes https://github.com/guzzle/psr7/issues/13.
I realize there is already a PR for that (https://github.com/guzzle/psr7/pull/32) but it seams sort-of abandoned. I was waiting on that functionality as I need it in one of my projects, so seeing this PR stagnate I decided to reimplement it myself. 
It has almost full test coverage, the $\_FILES array conversion handles more cases, the moveTo method is according to spec and I try to use the already available functionality as much as possible
Merry Christmas :christmas_tree: :)
=> ServerRequest and UploadedFIle Implementation

src/Uri.php, tests/UriTest.php
As much as it seems these implementations really don't want to be friendly to extension, this change stands on its own as being more accurate with regards to using the `static` keyword. That being, there is no reason to use the `static` keyword when referring to private members.
For the situation in which `Uri` is extended, there is a fatal that can occur when a non-standard port is provided due to the `static` keyword attempting to access the private property `$schemes` in `Uri::isNonStandardPort()`.
Stack trace:
> PHP  15. GuzzleHttp\Psr7\Uri->__construct() ...extension...
> PHP  16. GuzzleHttp\Psr7\Uri->applyParts() ...guzzlehttp/psr7/src/Uri.php:54
> PHP  17. GuzzleHttp\Psr7\Uri->filterPort() ...guzzlehttp/psr7/src/Uri.php:449
> PHP  18. GuzzleHttp\Psr7\Uri::isNonStandardPort() …
=> Remove use of late static binding against private members in Uri.

src/functions.php, tests/FunctionsTest.php
I haven't found any particular limitation in spec that doesn't allow using `_` as an example in request method.
Browsers and web servers (Nginx and Apache2 at least) all work fine with such methods, so we need to support it here as well.
=> Added support for request methods that contain something other that just letters

src/Uri.php, src/functions.php, tests/StreamWrapperTest.php, tests/UriTest.php
1. All occurences of `empty($this->password)` or `if ($this-password)` are broken because it will not correctly work with `'0'` string which is regarded as empty in PHP
2. Fix `Uri::__toString` according to PSR-7/RFC-3986
3. Refactor port handling
4. Improve tests
5. fix tests under windows
=> Fix URI parts when '0' and assembly according to PSR-7

src/Uri.php, tests/UriTest.php
This PR is based on #81 and will be rebased when #81 is merged.
- unify wrong type handling for uri components: `withHost` didn't check the type for example, but `withPath` did. And `withQuery` checked for `__toString` which is not specified in PSR-7.
- remove magic trimming of component delimiters which is not according to PSR-7. This magic has been removed in https://github.com/php-fig/fig-standards/pull/503
- add missing lowercase normalization for host
- improve encoding tests
- use possessive quantifier to encode uri (`++`) to prevent regex backtracking which improves performance
=> remove magic trimming of URI component delimiters

src/MessageTrait.php, src/Request.php, src/Response.php, src/ServerRequest.php, src/Uri.php, tests/FunctionsTest.php, tests/RequestTest.php, tests/ResponseTest.php
- `withAddedHeader` with a different case would not correctly merge headers. this test failed:
```
$r = new Response(200, ['Foo' => 'Bar']);
$r2 = $r->withAddedHeader('foO', 'Baz');
$this->assertSame(['Foo' => ['Bar', 'Baz']], $r2->getHeaders());
```
- fixes #80 and includes tests
- trim header values only and consistently. it was done in `withHeader` but not in `withAddedHeader`
- fix '0' problem for response reason
- improve tests to cover many more cases
The new headers handling is an optimized version of https://github.com/zendframework/zend-diactoros/blob/master/src/MessageTrait.php that does less `strtolower`
=> better implementation of headers handling

README.md
This was added in 1.3 right? So bit confusing when reading the readme :)
Also, docs for those functions should still be added.
=> Remove message about partial implementation

README.md, src/Uri.php, src/functions.php, tests/UriTest.php
This way you can pass they key/value both in encoded as well as decoded form to those methods.
This is consistent with `withPath`, `withQuery` etc.
Before it was handling a mix of it. It would encode the delimiters but not other chars. So it would not correctly identify existing query params to replace/remove. See tests.
Also fixes some docs in the readme.
=> Fix handling of encoding in Uri::with(out)QueryValue

src/functions.php, tests/FunctionsTest.php
@Tobion 
By the way, I'm getting this test failure when running the tests locally on my PHP 7.0.3:
```
1) GuzzleHttp\Tests\Psr7\UriTest::testUriComponentsGetEncodedProperly with data set #1 ('/€?€#€', '/%E2%82%AC', '%E2%82%AC', '%E2%82%AC', '/%E2%82%AC?%E2%82%AC#%E2%82%AC')
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-/%E2%82%AC
+/%E2_%AC
/Users/dowling/projects/guzzle/psr7/tests/UriTest.php:473
```
=> No longer reading maxLen all into memory when copying stream

src/Uri.php, tests/UriTest.php
Trying to test an html parser with local saved versions fails because the Uri re-constructs the `file` uri as `file:/home/...` instead of `file:///home/...`, which is necessary for php functions such as `fopen,` `file_get_contents` or `is_file`.
Using the scheme-less syntax, like `/home/...` might work for some, but it does not solve the issue when we are using a scheme.
So I added an exclusion when the file scheme is used, so we do add `//` even when authority is empty.
=> Fix support for reconsturcting localhost file scheme

.travis.yml, src/LimitStream.php, tests/CachingStreamTest.php, tests/LimitStreamTest.php, tests/UploadedFileTest.php
Fixes #49
The test doesn't make sense as it's an implementation detail of PHP that is not our task to test it (esp. not via the LimitStream)
=> remove failing hhvm test that is also not to be tested by LimitStream

src/Stream.php, tests/StreamTest.php
- if `$length === 0` return empty string
- if `$length < 0` throw `RuntimeException`
- if `fread` return false throw RuntimeException
Add PHPUnit tests
Issue #119
=> Suppress warning for `Stream::read` method call

src/MultipartStream.php, tests/UploadedFileTest.php
cf http://blog.kevingomez.fr/til/2015/07/26/why-is-uniqid-slow/
=> Added more entropy to uniqid

src/ServerRequest.php, tests/ServerRequestTest.php
this also ensures the returned URI is in absolute form which makes more sense is is according to https://tools.ietf.org/html/rfc7230#section-5.5
It also accepts other non-"on" values for HTTPS server config which is according to the doc http://php.net/manual/en/reserved.variables.server.php:
> 'HTTPS': Set to a non-empty value if the script was queried through the HTTPS protocol.
Fixes #117, #116, #128, #130
=> fix ServerRequest::getUriFromGlobals when Host header contains port

src/MessageTrait.php, src/functions.php
Fix parse response header in case something like this:
HTTP/1.1 404
Date: Mon, 20 Jun 2016 17:34:12 GMT
Content-Type: text/html
Content-Length: 193
Connection: close
Server: IdeaWebServer/v0.80
=> Fix parse response header status without description

src/Uri.php, tests/UriTest.php
Fixes #138 and will be released as 1.4.1
=> Remove common BC break for relative path with authority and trigger deprecations instead

src/Uri.php
There are two static methods in `GuzzleHttp\Psr7\Uri` that always trigger immediately silenced errors. This introduces a runtime performance penalty to communicate the same information as the already-present `@deprecated` annotation, which is used by IDEs and static analysis tools to notify developers at dev time that a deprecated method is being used.
I've received multiple reports of the silenced `trigger_error` call causing errors in production for users who define custom error handlers, e.g. https://github.com/aws/aws-sdk-php/issues/1198
/cc @mtdowling @Tobion
=> Rely on `@deprecated` annotation instead of triggering and immediately silencing a deprecation notice

src/functions.php, tests/FunctionsTest.php
readline() currently returns an empty string on EOF (rather than false).
Currently, comments suggest that the implementation works like fgets().
Incorrect usage :
```
while (($line = readline($stream, 2048)) !== false) {
// Code loops forever
}
```
Correct usage:
```
// Read until the stream is closed
while (!$stream->eof()) {
// Read a line from the stream
$line = $stream->readLine();
}
```
=> Bool return type not possible in readline()

.travis.yml, CHANGELOG.md, src/AppendStream.php, src/Stream.php, tests/AppendStreamTest.php, tests/FnStreamTest.php, tests/NoSeekStreamTest.php, tests/StreamTest.php
- Fix AppendStream::detach to not close the resource
- Clarify exception message when stream is detached. Some methods said "Stream is detached", while other methods used a different error. E.g. Stream::write said "Cannot write to a non-writable stream" which is misleading when is stream is actually detached.
- added a test for #129 behavior
- fix hhvm travis
=> Fix AppendStream::detach to not close the resource and exception messages

src/functions.php
Since you are returning two type of stream (PumpStream and Stream) you should either have as docblock the `StreamInterface` or `Stream|PumpStream`
=> Fix the return typehint in docblock of stream_for function

src/FnStream.php, tests/FnStreamTest.php
Given the fact that this is a very popular package, I would suggest to not allow an unserialization for FnStream.
A serialize of this type is pointless anyway as serialization of closures are not allowed.
The FnStream combined with an unserialize of a string inputted by a client could result in executing code via the destructor.
Of course people should be careful what they do with the unserialize function, but this pull request would at least limit the attack surface.
People have been using this do demonstrate CVE-2017-6920 (https://paper.seebug.org/334/)
=> FnStream should never be unserialized

src/ServerRequest.php
=> bugfix in ServerRequest::getUriFromGlobals() method for url https://site.com/path?continue=https://site.com/widget?param=1

src/InflateStream.php, tests/InflateStreamTest.php
When a stream is wrapped with InflateStream is not preserving isSeekable flag, breaking some outer decorators.
I did a research on the topic and seems that PHP custom wrappers are always seekable.
=> Fix InflateStream not preserving isSeekable.

src/StreamWrapper.php, tests/StreamWrapperTest.php
This PR implements the missing `StreamWrapper::url_stat()` method as documented [here](http://php.net/manual/en/streamwrapper.url-stat.php). In addition, it adds a helper method `createStreamContext()` to allow userland code to perform the `fopen` operation for a stream.
Motivation: Many php core functions and extensions are able to operate on php streams, but they demand a URI and a stream context. `StreamWrapper::getResource()` however gives me an open stream resource which is useless in that case.
One example is the `XMLReader` class, which I find very useful for processing a large HTTP response body containing XML. With the current state of guzzle/psr7, I would try to open an XML Reader like this:
```php
<?php
use GuzzleHttp\Psr7\StreamWrapper;
StreamWrapper::register(); …
```
=> Implement StreamWrapper::url_stat()

src/functions.php, tests/FunctionsTest.php
Basically I never understood why this function was added in RequestException class https://github.com/guzzle/guzzle/blob/master/src/Exception/RequestException.php#L123 and why only for the responses.
I thought that this is a helpful function that could be added in the functions file.
=> Added a function in order to get the message body summary

src/functions.php
As per function's code - `stream_for` accepts `Iterator`, which is not mentioned in acceptable types for `$resource`
=> stream_for docblock: `$resource` accepts Iterator

src/functions.php
Fix of phpstan/phpstan error: `Parameter #2 $urlEncoding of function GuzzleHttp\Psr7\parse_query expects bool|string, int given.`
=> Parse query expects int

src/Stream.php, tests/StreamTest.php
> PHP 7.1 gives rb+. But in this array there is only r+b variant. This fix will help to make Flystem aws s3 woring on php 7.1.
> 
> Without this commit Stream says, that stream is not readable, when it gives rb+ (which means it is readable). There is no problem on older php versions.
See #205 #183
=> Hotfix (hardcode) for working on php 7.1

src/ServerRequest.php, src/functions.php, tests/FunctionsTest.php
Trying to fix https://github.com/guzzle/psr7/issues/177. The `modify_request` function removes the `uploadedFile` array out of the `ServerRequest` because it returns `new ServerRequest` and `ServerRequest` object doesn't have `uploadedFile` array as an argument in the constructor.
=> Fix modify_request function to respect ServerRequest with UploadedFiles

tests/bootstrap.php
When I try to run a single file from my PHPStorm I get:
This fixes the issue @carusogabriel if he can check also... (was the one adding the file)
=> Fix tests bootstraping

src/functions.php, tests/FunctionsTest.php
I have no excuses.
Previous [PR](https://github.com/guzzle/psr7/pull/232) I did used the dev version of mine to see if the tests of guzzle [here](https://github.com/guzzle/guzzle/pull/2227) are passing but through my PHPStorm I checked only that specific test.. 
After tagging the 1.5.1 another test was failing because of the missing code on this PR. At least this is not a "bug" as the previous one and can wait for the next release :( 
So sorry...
=> When body size is zero return null on get_message_body_summary function

src/functions.php
The WEBP image format does not yet have an official IANA MIME type definition.
However, the same can be said about video/webm which is adopted in a similar width as WEBP.
Apache web server, python web server and many more has adopted the MIME type image/webp for the WEBP image format, so it is only logical to assume its validity at the same level as WEBM video.
=> Add MIME type for WEBP image format

src/Uri.php, tests/UriTest.php
=> URL-encodes the `userInfo` component of an URI

composer.json
It is necessary because `gzencode ()` is used in tests
=> Fix composer.json: add `ext-zlib` to `require-dev` section

src/Stream.php
Fix error:
```
Exception: fseek() expects parameter 3 to be int, unknown given in 
/var/www/project/vendor/guzzlehttp/psr7/src/Stream.php:206
```
=> Fix error in PHP 7.3

src/ServerRequest.php
According to the PHP documentation reading from the same php://input
stream is not possible. Even reading from separate streams is
SAPI dependent.
http://php.net/manual/de/wrappers.php.php#wrappers.php.input
This change adds a CachingStream wrapping the default stream
when using ServerRequest::fromGlobals to allow subsequent
reads.
Fixes #186
=> Fix subsequent reads from php://input in ServerRequest

src/Stream.php, tests/StreamTest.php
=> Fix stream modes

src/AppendStream.php, src/FnStream.php, src/PumpStream.php, src/Stream.php, src/StreamDecoratorTrait.php, tests/AppendStreamTest.php, tests/FnStreamTest.php, tests/PumpStreamTest.php, tests/StreamTest.php
On `StreamDecoratorTrait` I saw a comment about this [bug](https://bugs.php.net/bug.php?id=53648)
I made a test and I saw that the same error is raised with throwables as well..
My test:
``` php
class MyClass
{
public function __toString()
{
try {
throw new Error('whatever');
} catch (Exception $e) {
return '';
}
}
}
$c = new MyClass();
(string)$c;
```
Result: `Method MyClass::__toString() must not throw an exception, caught Error: whatever .... ... ... `
**Important** not sure if `FnStream` should also have a `try..catch`. At the moment it does not.
=> __toString functions must catch also throwables

src/Uri.php, tests/UriTest.php
Listening on an unix socket reports port number 0, which is interpreted as an invalid argument.
=> Change minimal port number to 0 (unix socket)

src/MessageTrait.php, src/Request.php, src/Response.php, tests/RequestTest.php, tests/ResponseTest.php
=> Assert values according to PSR standard

src/MessageTrait.php, tests/ResponseTest.php
This is not according to PSR-7 which says `@param string|string[] $value Header value(s).` but for BC and missing type declarations it makes sense.
Fixes #282
=> Accept null and bool header values again

src/Uri.php
Some libraries perform many implicit calls to `Uri::__toString()`, which heavily affect their performance.
For example, [in spatie/crawler](https://github.com/spatie/crawler/blob/67974a810f6a342c333c4e348fcfad7c1375ffde/src/CrawlQueue/CollectionCrawlQueue.php#L103-L117):
```php
protected function contains($collection, CrawlUrl $searchCrawlUrl): bool
{
foreach ($collection as $crawlUrl) {
if ((string) $crawlUrl->url === (string) $searchCrawlUrl->url) {
return true;
}
}
return false;
}
```
Of course, this specific example could be improved by moving the rightmost `(string)` conversion out of the loop; but the leftmost conversion is harder to optimize: every call to `contains()` will perform a `(string)` conversion on every element in the collection, making it harder to optimize without …
=> Cache __toString() representation

src/Response.php
I added the 510 - Not Extended HTTP Response Phrase, as defined on the [RFC2774](https://tools.ietf.org/html/rfc2774#section-7).
Should it be merged? Maybe.
RFC2774 status is "Experimental" since February 2000, but I haven't found any conflict with other status codes. I'd say it'd be better to use it since some servers might respond with this status (I'm dealing with an API which does, and got quite confuse with an empty reason phrase on my logs).
=> Added 510 - Not Extended HTTP Response Phrase

phpstan-baseline.neon
PHPStan is no longer complaining about these things. Not complaining about something in the baseline file is treated as an error, which is causing all incoming PRs to 2.0.x-dev to fail.
=> [2.0] Fixed static analysis

src/InflateStream.php, tests/InflateStreamTest.php
I figured that `InflateStream` is only capable of inflating gzip format (10 bytes header + optional meta). However, [it is meant to be used for inflating deflate](https://github.com/guzzle/guzzle/blob/master/src/Handler/StreamHandler.php#L163) data (zlib format - 2 bytes header).
Since this is using zlib stream filter, it is possible to pass `window=15+32` as parameter and let zlib detect file header so it can consume both zlib (deflate) and gzip data.
As bonus point, previous implementation was skipping only filename if it's present, but compressed file may contain more optional metadata - variable length comment, extra fields, header crc16. If any of these were present, existing code chokes and outputs empty string.
=> Allow inflation of deflate (zlib format) streams

README.md, src/functions.php
I noticed this function was added recently (ish), but was never documented, like the other functions.
=> [1.6] Document get_message_body_summary

src/Stream.php, tests/StreamTest.php
=> Fix converting a non-seekable stream to a string for 1.x

src/MessageTrait.php, tests/ResponseTest.php
This PR for https://github.com/php-http/psr7-integration-tests/pull/10 + https://github.com/php-http/psr7-integration-tests/pull/43 should fix https://github.com/guzzle/psr7/issues/249
=> ignore array keys in header values for correct merging

src/Response.php
`$statusCode` assignment can be safely removed as the constructor overrides it.
`$reasonPhrase` assignment can be safely removed as the constructor overrides it and function default parameter also overrides it.
=> Remove redundant class properties assignment

src/functions.php, tests/FunctionsTest.php
I've noticed that if a request throws an exception and if the response body includes the character `’`, the function `get_message_body_summary()` **will return null**.
The expected result should be the string including **the special character**.
This happens due to the regex used to match any printable character lacks of the `/u` flag.
For example, this returns `1`, forcing `get_message_body_summary()` to return `null`:
```
preg_match('/[^\pL\pM\pN\pP\pS\pZ\n\r\t]/', '’')
```
Other multibyte characters like ௵ and ဪ also trigger this issue.
Adding the `/u` flag solves this issue.
=> Include '/u' flag on summary regex

src/AppendStream.php, src/BufferStream.php, src/CachingStream.php, src/DroppingStream.php, src/FnStream.php, src/InflateStream.php, src/LazyOpenStream.php, src/LimitStream.php, src/MultipartStream.php, src/NoSeekStream.php, src/PumpStream.php, src/StreamWrapper.php
the generic classes like request, response, uri, stream are not final as there seem to be use-cases to extend them
fixes #286
=> make special purpose classes final

tests/BufferStreamTest.php, tests/CachingStreamTest.php, tests/DroppingStreamTest.php, tests/FnStreamTest.php, tests/FunctionsTest.php, tests/InflateStreamTest.php, tests/LazyOpenStreamTest.php, tests/LimitStreamTest.php, tests/MultipartStreamTest.php, tests/PumpStreamTest.php, tests/ServerRequestTest.php, tests/StreamDecoratorTraitTest.php, tests/StreamTest.php, tests/StreamWrapperTest.php, tests/UploadedFileTest.php
So the thing is that there are assertions happening between objects. Hence the rule of assertSame can not be enforced.
Let me know WDYT.
=> Use assertSame instead of assertEquals

.travis.yml, tests/StreamTest.php
This tests on the same versions as https://github.com/guzzle/promises/pull/110 (as well as 5.4), in particular, testing on HHVM 3 properly.
=> CI and HHVM fixes

.travis.yml, composer.json, phpunit.xml.dist, tests/AppendStreamTest.php, tests/BaseTest.php, tests/BufferStreamTest.php, tests/CachingStreamTest.php, tests/FnStreamTest.php, tests/Helpers.php, tests/LazyOpenStreamTest.php, tests/LimitStreamTest.php, tests/MessageTest.php, tests/MultipartStreamTest.php, tests/NoSeekStreamTest.php, tests/RequestTest.php, tests/ResponseTest.php, tests/ServerRequestTest.php, tests/StreamDecoratorTraitTest.php, tests/StreamTest.php, tests/StreamWrapperTest.php, tests/UploadedFileTest.php, tests/UriTest.php, tests/UtilsTest.php, tests/bootstrap.php
We support PHP 5.4, so Symfony's bridge is not so easy. Never the less, there was already phpunit work around code I could just expand upon. After updating the tests to run on all versions of PHPUnit, they pass on PHP 8.0 with no src changes.
=> [1.x] Run tests on PHP 8.0

tests/UriTest.php
PHP 7.3.24, 7.4.12 and 8.0.0RC1 or higher now allow zero as a port: https://github.com/php/php-src/commit/81b2f3e5d9fcdffd87a4fcd12bd8c708a97091e1.
=> Fixed bad test

.github/workflows/integration.yml, phpunit.xml.dist, src/Utils.php
Request created from globals always return empty string as a body.
to test it try create run the following code:
```
$request = \GuzzleHttp\Psr7\ServerRequest::fromGlobals();
var_dump($request->getBody()->getContents());
```
and do a POST request with non empty body.
Unfortunately I did not find the way to create a unit test for that case because of this condition:
```
\stream_get_meta_data($resource)['uri'] === 'php://input'
```
there is no way to create a mock of `$resource`
=> fix: seek stream cloned from php input to begining

src/Query.php, tests/QueryTest.php
=> [Query::build()] Make sure booleans are treated as ints

.github/workflows/bc.yml
This make sure we dont break things accidentally.
=> Adding tests for BC checks

src/Utils.php, tests/UtilsTest.php
=> Fix `Utils::modifyRequest` dropping `ServerRequest` attributes

CHANGELOG.md
There is no need for these links. Github UI or git will provide this information.
=> Removed broken links

src/Utils.php
fix #411 in 1.x branch for `"php": ">=5.4.0",`
=> Avoid no-url index in stream_get_meta_data

.github/FUNDING.yml, .github/stale.yml, LICENSE, README.md, composer.json
I'm sending this to 1.x rather than 2.x because I'm also planning on fixing PHP 8.1 support on the 1.x line. It still gets a lot of use, including by the official AWS SDK.
=> Updated docs

CHANGELOG.md, src/Exception/MalformedUriException.php, src/Uri.php, tests/UriTest.php
This replaces the generic `InvalidArgumentException`.
Closes #426
=> Introduce MalformedURIException

src/AppendStream.php, src/BufferStream.php, src/FnStream.php, src/PumpStream.php, src/ServerRequest.php, src/Stream.php, src/StreamDecoratorTrait.php
This documents the return type for methods implementing PSR-7 interfaces, but where the return type is not compatible with PHP 7.2.
Besides making the return type more descriptive when reading the method definition, this also suppresses type deprecation notices when using guzzle/psr7 with Symfony 5.4+.
=> Add `@return` to define the return type for non-PHP 7.2 compatible types

src/Request.php
* I just removed the backslash on the InvalidArgumentException class because it is  already imported by the use keyword at the beginning.
=> Remove unneeded backslash

src/Utils.php, tests/UtilsTest.php
Related to https://github.com/guzzle/psr7/issues/429. Allows for validation to happen downstream instead of crashing on an internal error. Also, the type information on this function technically says any kind of array key is allowed, sooo. ;)
As to why fix this only on 2.x? On 1.x, it was actually doing casting for us, so the behaviour there was to remove keys with integer value 1 if the string key was '1'. This PR instead skips over integer keys, which I think is the better behaviour, but also technically a breaking change. Since this is not working at all in 2.0.0, we're good to make that change in 2.1.0. :trollface:
=> Make caseless remove robust

CHANGELOG.md, src/CachingStream.php, tests/CachingStreamTest.php
⚠️ Should be merged without squashing.
=> Merge 1.x -> master

src/Query.php, tests/QueryTest.php
With a query like `q&q=a`, the first value (`null`) got lost due to an `isset()` call.
=> Fix missing null in `Query::parse()` with multiple values

src/Uri.php
This is not a breaking change - this is new code, not yet released. This is a bug fix, however. PHP 8.1 insists on there being a return type on this method.
---
Closes https://github.com/guzzle/psr7/issues/466.
=> Added missing return type

src/ServerRequest.php
Fix a small typo I've noticed in the PHP doc.
`a array` => `an array`
Hope It still helps 🙂
=> Fixed typo in php docBlock

phpstan-baseline.neon, src/Utils.php
There is a special case for `php://input` as it behaves differently than other streams apparently. As a result, that stream is put into a `php://temp` stream. However, the original implementation reads in the entire request into RAM, essentially removing streaming functionality. That results into out of memory errors, if the request is large enough.
refs #354,  [#2276@guzzle](https://github.com/guzzle/guzzle/issues/2276)
=> Fixed reading in the entire request into RAM

src/Header.php, tests/HeaderTest.php
=> Fix parsing in `Header::normalize()`

src/Message.php, src/MessageTrait.php, tests/MessageTest.php
=> Fix Message::parseRequestUri() for numeric headers

.github/workflows/ci.yml, .github/workflows/integration.yml
This is no longer required since PHPUnit 9.5.23.
=> Stop mimicking PHP 8.1 in CI

README.md, src/Header.php
`splitList()` is a replacement for `normalize()`. It was forgotten to adjust
the README.md in guzzle/psr7#477.
=> Replace Header::normalize() by Header::splitList() in README

CHANGELOG.md
Quite late, I know, but I just upgraded Guzzle 1 -> 2 in an app and noticed errors about undefined functions. When going through the changelogs at the same time I thought "they must be still there, since only `Guzzle\Psr7` functions were removed" 😅
I thought then that it might make sense to still adapt this in case other people check old breaking changes (in the current branch's CHANGELOG at least) and make a similar mistake.
=> Fix namespace in changelog entry for 2.0.0

README.md
On PHP 8.2, if you don't explicitly declare the property, you will get an error like `Deprecated: Creation of dynamic property EofCallbackStream::$stream is deprecated`
From what I can tell, other usages in this code base (e.g. https://github.com/guzzle/psr7/blob/b4719a1/src/DroppingStream.php#L15-L21) explicitly add a `$stream` property when they're using `StreamDecoratorTrait`.
=> Fixed readme `EofCallbackStream` example
